### ISSUE TITLE
NEW gestion des numéros de versions

### ISSUE THREAD

**Issue by lvessiller-opendsi** [ATM-Consulting/dolibarr_module_propalehistory#38]
@atm-john 

Lorsqu'on plusieurs versions sur un même devis et que l'on restaure une des versions, il serait bien de garder cette version sur la fiche et le PDF généré au lieu d'avoir un nouveau numéro de version auto-incrémenté.

Par exemple si on part du devis "DEV2201-0001" et qu'on a archivé deux versions :
- Version 1 du devis "DEV2201-0001"
- Version 2 du devis "DEV2201-0001"

On voit bien les différentes versions dans la liste.
On veut alors revenir sur la version 2, on sélectionne cette version et on clique sur le bouton "Visualiser".
Ensuite lorsqu'on clique sur "Restaurer" alors on voit sur la fiche qu'on est sur une nouvelle version "DEV2201-0001 / 3" et lorsqu'on génère le PDF on a également en référence "DEV2201-0001 / 3".

Serait-il possilbe de garder le numéro de version 2 et non partir sur un nouveau numéro de version ?

**Comment by atm-john** [comment]
Clôture  de l'issue suite PR mergée
