### ISSUE TITLE
Module category "ATM" is inconsistent

### ISSUE THREAD

**Issue by cfoellmann** [ATM-Consulting/dolibarr_module_propalehistory#39]
Hi @ATM-Consulting people, @atm-john,

the module category for ATM is all over the place. SEE this:

![image](https://user-images.githubusercontent.com/1256090/151384028-762c5436-955c-4a3a-87a6-a3bb211b1f3e.png)

Maybe you could start consolidating 
https://github.com/ATM-Consulting/dolibarr_module_propalehistory/blob/b812f2bd3ac2c934b49895b5887f860c6afad264/core/modules/modPropalehistory.class.php#L56

as just
```php
$this->family = 'ATM Consulting';
```

**Comment by atm-john** [comment]
Nous avons commencé l'année dernière un changement de nos familles de modules, nous avons plus de 400 modules et les instances de nos clients ont généralement 20 modules installés au minimum, donc nous nous sommes séparés mais changer tous nos modules prend du temps.
